name: Build and Deploy Portfolio

on:
  push:
    branches:
      - main # Cambia a tu rama principal si es diferente
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Configurar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # Usa la versión compatible con Astro
          cache: 'npm'

      # Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Generar la aplicación estática
      - name: Build the project
        run: npm run build

      # Deploy a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist